export type University =
  | "HSE"
  | "MSU"
  | "MIPT"
  | "BMSTU"
  | "ITMO"
  | "SPbU"
  | "NSU"
  | "MEPHI"
  | "SPbPU"
  | "INNO"
  | "SKOLTECH"
  | "MISIS"
  | "MIREA"
  | "LETI"
  | "TSU"
  | "TPU"
  | "TUSUR"
  | "URFU"
  | "KFU"
  | "NNSU"
  | "SAMSU"
  | "SFU"
  | "FEFU"
  | "SUAI"
  | "RUDN"
  | "REU"
  | "FA"
  | "MAI"
  | "MEI"
  | "MTUCI";

export type Direction =
  | "Backend"
  | "Frontend"
  | "Data/ML"
  | "AI"
  | "DevOps"
  | "Mobile"
  | "Security";

export type WorkFormat = "Remote" | "Hybrid" | "Onsite";
export type Paid = "Paid" | "Unpaid";

export type City = "Any" | "Moscow" | "SPb" | "Kazan" | "Novosibirsk" | "Yekaterinburg";

export type Internship = {
  id: string;
  company: string;
  roleTitle: string;

  salaryLabel: string; // e.g. "от 80 000 ₽" | "договорная" | "оплачиваемая"
  salaryMin?: number; // RUB
  salaryMax?: number; // RUB

  paid: Paid;
  format: WorkFormat;
  city: City;
  direction: Direction;

  universities: University[];
  programs: string[]; // lightweight: e.g. ["ФКН", "ВМК", "ПМИ"]
  stack: string[]; // e.g. ["C#", ".NET", "SQL"]

  // Recruiter requirements
  courseMin?: number; // 1..6
  courseMax?: number; // 1..6
  minGpa?: number; // 0..10

  season: string; // e.g. "Лето 2026"
  duration: string; // e.g. "3 месяца"
  locationLabel: string; // e.g. "Москва" | "Санкт-Петербург" | "Удаленно"
  postedAtISO: string; // ISO date string
  asap?: boolean; // "как можно раньше"

  shortPitch: string;
  about: string;
  responsibilities: string[];
  requirements: string[];
  niceToHave: string[];

  apply: {
    telegramUrl: string;
    email: string;
  };

  hot?: boolean;
  userCreated?: boolean;
};

export const UNIVERSITY_LABEL: Record<University, string> = {
  HSE: "ВШЭ",
  MSU: "МГУ",
  MIPT: "МФТИ",
  BMSTU: "МГТУ",
  ITMO: "ИТМО",
  SPbU: "СПбГУ",
  NSU: "НГУ",
  MEPHI: "МИФИ",
  SPbPU: "СПбПУ",
  INNO: "Иннополис",
  SKOLTECH: "Сколтех",
  MISIS: "МИСИС",
  MIREA: "МИРЭА",
  LETI: "ЛЭТИ",
  TSU: "ТГУ",
  TPU: "ТПУ",
  TUSUR: "ТУСУР",
  URFU: "УрФУ",
  KFU: "КФУ",
  NNSU: "ННГУ",
  SAMSU: "СамГУ",
  SFU: "СФУ",
  FEFU: "ДВФУ",
  SUAI: "ГУАП",
  RUDN: "РУДН",
  REU: "РЭУ",
  FA: "ФинУнивер",
  MAI: "МАИ",
  MEI: "МЭИ",
  MTUCI: "МТУСИ",
};

export type UniversityMeta = {
  id: University;
  short: string;
  full: string;
  aliases: string[];
};

export const UNIVERSITIES: UniversityMeta[] = [
  {
    id: "HSE",
    short: "ВШЭ",
    full: "Национальный исследовательский университет «Высшая школа экономики»",
    aliases: ["НИУ ВШЭ", "Высшая школа экономики", "HSE", "Higher School of Economics"],
  },
  {
    id: "MSU",
    short: "МГУ",
    full: "Московский государственный университет имени М. В. Ломоносова",
    aliases: ["Ломоносов", "MSU", "МГУ им. Ломоносова", "Московский государственный университет"],
  },
  {
    id: "MIPT",
    short: "МФТИ",
    full: "Московский физико-технический институт (национальный исследовательский университет)",
    aliases: ["Физтех", "MIPT", "МФТИ (Физтех)"],
  },
  {
    id: "BMSTU",
    short: "МГТУ",
    full: "МГТУ им. Н. Э. Баумана (Московский государственный технический университет)",
    aliases: ["Бауманка", "BMSTU", "Бауманский", "МГТУ Баумана"],
  },
  {
    id: "ITMO",
    short: "ИТМО",
    full: "Университет ИТМО",
    aliases: ["ITMO", "Санкт-Петербургский ИТМО", "Университет информационных технологий, механики и оптики"],
  },
  {
    id: "SPbU",
    short: "СПбГУ",
    full: "Санкт-Петербургский государственный университет",
    aliases: ["SPBU", "СПб государственный университет", "Питерский госуниверситет"],
  },
  {
    id: "NSU",
    short: "НГУ",
    full: "Новосибирский национальный исследовательский государственный университет",
    aliases: ["NSU", "Новосибирский государственный университет"],
  },
  {
    id: "MEPHI",
    short: "МИФИ",
    full: "Национальный исследовательский ядерный университет «МИФИ»",
    aliases: ["НИЯУ МИФИ", "MEPHI", "Ядерный университет"],
  },
  {
    id: "SPbPU",
    short: "СПбПУ",
    full: "Санкт-Петербургский политехнический университет Петра Великого",
    aliases: ["Политех", "Политех Петра", "SPBPU", "Политехнический университет Петра Великого"],
  },
  {
    id: "INNO",
    short: "Иннополис",
    full: "Университет Иннополис",
    aliases: ["Innopolis", "INNO", "Иннополис университет"],
  },
  {
    id: "SKOLTECH",
    short: "Сколтех",
    full: "Сколковский институт науки и технологий",
    aliases: ["Skoltech", "SKOLTECH", "Сколково институт", "Сколково"],
  },
  {
    id: "MISIS",
    short: "МИСИС",
    full: "Национальный исследовательский технологический университет «МИСИС»",
    aliases: ["НИТУ МИСИС", "MISIS"],
  },
  {
    id: "MIREA",
    short: "МИРЭА",
    full: "Российский технологический университет МИРЭА (РТУ МИРЭА)",
    aliases: ["РТУ МИРЭА", "MIREA", "РТУ", "МИРЭА РТУ"],
  },
  {
    id: "LETI",
    short: "ЛЭТИ",
    full: "Санкт-Петербургский государственный электротехнический университет «ЛЭТИ»",
    aliases: ["СПбГЭТУ ЛЭТИ", "LETI", "Электротехнический университет ЛЭТИ"],
  },
  {
    id: "TSU",
    short: "ТГУ",
    full: "Томский государственный университет",
    aliases: ["TSU", "Томский госуниверситет"],
  },
  {
    id: "TPU",
    short: "ТПУ",
    full: "Томский политехнический университет",
    aliases: ["TPU", "Томский политех"],
  },
  {
    id: "TUSUR",
    short: "ТУСУР",
    full: "Томский государственный университет систем управления и радиоэлектроники",
    aliases: ["TUSUR", "Томский ТУСУР"],
  },
  {
    id: "URFU",
    short: "УрФУ",
    full: "Уральский федеральный университет имени первого Президента России Б. Н. Ельцина",
    aliases: ["URFU", "Уральский федеральный университет", "Ельцин УрФУ"],
  },
  {
    id: "KFU",
    short: "КФУ",
    full: "Казанский (Приволжский) федеральный университет",
    aliases: ["KFU", "Казанский федеральный университет"],
  },
  {
    id: "NNSU",
    short: "ННГУ",
    full: "Нижегородский государственный университет имени Н. И. Лобачевского",
    aliases: ["ННГУ им. Лобачевского", "Lobachevsky University", "Нижегородский университет", "NNSU"],
  },
  {
    id: "SAMSU",
    short: "СамГУ",
    full: "Самарский национальный исследовательский университет имени академика С. П. Королева",
    aliases: ["Самарский университет", "Samara University", "SAMSU"],
  },
  {
    id: "SFU",
    short: "СФУ",
    full: "Сибирский федеральный университет",
    aliases: ["SFU", "Сибирский федеральный"],
  },
  {
    id: "FEFU",
    short: "ДВФУ",
    full: "Дальневосточный федеральный университет",
    aliases: ["FEFU", "Дальневосточный федеральный"],
  },
  {
    id: "SUAI",
    short: "ГУАП",
    full: "Санкт-Петербургский государственный университет аэрокосмического приборостроения",
    aliases: ["SUAI", "СПбГУАП", "ГУАП Санкт-Петербург"],
  },
  {
    id: "RUDN",
    short: "РУДН",
    full: "Российский университет дружбы народов",
    aliases: ["RUDN", "Университет дружбы народов", "РУДН имени Патриса Лумумбы"],
  },
  {
    id: "REU",
    short: "РЭУ",
    full: "Российский экономический университет имени Г. В. Плеханова",
    aliases: ["РЭУ им. Плеханова", "Plekhanov University", "REU"],
  },
  {
    id: "FA",
    short: "ФинУнивер",
    full: "Финансовый университет при Правительстве Российской Федерации",
    aliases: ["Финансовый университет", "Financial University", "FA", "Финуниверситет"],
  },
  {
    id: "MAI",
    short: "МАИ",
    full: "Московский авиационный институт (национальный исследовательский университет)",
    aliases: ["MAI", "Московский авиационный институт"],
  },
  {
    id: "MEI",
    short: "МЭИ",
    full: "Национальный исследовательский университет «МЭИ»",
    aliases: ["MEI", "НИУ МЭИ", "Московский энергетический институт"],
  },
  {
    id: "MTUCI",
    short: "МТУСИ",
    full: "Московский технический университет связи и информатики",
    aliases: ["MTUCI", "Связи и информатики", "Университет связи"],
  },
];

export const UNIVERSITY_BY_ID: Record<University, UniversityMeta> = Object.fromEntries(
  UNIVERSITIES.map((u) => [u.id, u])
) as Record<University, UniversityMeta>;

export const UNIVERSITY_POPULAR: University[] = [
  "HSE",
  "MSU",
  "MIPT",
  "BMSTU",
  "ITMO",
  "SPbU",
  "MEPHI",
  "NSU",
  "SPbPU",
  "INNO",
  "SKOLTECH",
  "MISIS",
];

export const CITY_LABEL: Record<City, string> = {
  Any: "Любой",
  Moscow: "Москва",
  SPb: "Санкт-Петербург",
  Kazan: "Казань",
  Novosibirsk: "Новосибирск",
  Yekaterinburg: "Екатеринбург",
};

export const DIRECTION_LABEL: Record<Direction, string> = {
  Backend: "Backend",
  Frontend: "Frontend",
  "Data/ML": "Data/ML",
  AI: "AI",
  DevOps: "DevOps",
  Mobile: "Mobile",
  Security: "Security",
};

export const FORMAT_LABEL: Record<WorkFormat, string> = {
  Remote: "Удаленно",
  Hybrid: "Гибрид",
  Onsite: "Офис",
};

export const PAID_LABEL: Record<Paid, string> = {
  Paid: "Оплачиваемая",
  Unpaid: "Неоплачиваемая",
};

export const COURSE_CHOICES = [1, 2, 3, 4] as const;

export const STACK_TAGS = [
  "Git",
  "HTML",
  "CSS",
  "REST",
  "JSON",
  "C#",
  ".NET",
  "ASP.NET",
  "C++",
  "Python",
  "Go",
  "Java",
  "Kotlin",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Vue",
  "Node.js",
  "SQL",
  "PostgreSQL",
  "Redis",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Linux",
] as const;

export const PROGRAM_TAGS = [
  "ФКН",
  "ВМК",
  "ПМИ",
  "ПИ",
  "ИВТ",
  "КТ",
  "ФИВТ",
  "ФПМИ",
  "ПМИ (ИТМО)",
  "SE",
  "ИУ",
  "ИБ",
] as const;

export const INTERNSHIPS: Internship[] = [
  {
    id: "net-backend-hybrid-moscow",
    company: "NebulaSoft",
    roleTitle: "Junior C# / .NET Backend Intern",
    salaryLabel: "от 80 000 ₽",
    salaryMin: 80000,
    paid: "Paid",
    format: "Hybrid",
    city: "Moscow",
    direction: "Backend",
    universities: ["HSE", "MSU", "MIPT", "BMSTU", "MEPHI"],
    programs: ["ФКН", "ВМК", "ПМИ", "ПИ"],
    stack: ["C#", ".NET", "ASP.NET", "SQL", "PostgreSQL", "Docker"],
    courseMin: 3,
    courseMax: 4,
    minGpa: 7.5,
    season: "Лето 2026",
    duration: "3 месяца",
    locationLabel: "Москва",
    postedAtISO: "2026-02-03",
    asap: true,
    shortPitch:
      "Пишем сервисы для внутренней платформы. Дадим наставника, задачи уровня “реально в прод”.",
    about:
      "NebulaSoft строит внутреннюю платформу для команд разработки: деплой, мониторинг, доступы, аудит. Ищем стажера в backend на .NET.",
    responsibilities: [
      "Разрабатывать небольшие сервисы и API (ASP.NET Core)",
      "Писать SQL-запросы и миграции",
      "Добавлять метрики/логи и простые алерты",
      "Участвовать в ревью кода и разборе инцидентов",
    ],
    requirements: [
      "Уверенные основы C# и ООП",
      "Базовое понимание HTTP/REST",
      "SQL на уровне JOIN/индексов (или готовность быстро подтянуть)",
    ],
    niceToHave: ["Docker", "PostgreSQL", "Опыт с GitHub Actions или аналогами"],
    apply: {
      telegramUrl:
        "https://t.me/nebula_hr?text=Привет!%20Откликаюсь%20на%20стажировку%20Junior%20.NET%20Backend",
      email: "intern@nebulasoft.example",
    },
    hot: true,
  },
  {
    id: "frontend-remote-react",
    company: "CampusGrid",
    roleTitle: "Frontend Intern (React)",
    salaryLabel: "от 70 000 ₽",
    salaryMin: 70000,
    paid: "Paid",
    format: "Remote",
    city: "Any",
    direction: "Frontend",
    universities: ["HSE", "ITMO", "SPbU", "MSU", "NSU", "SPbPU"],
    programs: ["ФКН", "ИВТ", "КТ", "SE"],
    stack: ["TypeScript", "React", "Next.js"],
    courseMin: 1,
    courseMax: 3,
    minGpa: 6.5,
    season: "Весна 2026",
    duration: "2 месяца",
    locationLabel: "Удаленно",
    postedAtISO: "2026-02-01",
    shortPitch:
      "Собираем панель для учебных проектов. Нужно аккуратно верстать и не бояться состояния.",
    about:
      "CampusGrid делает инструменты для студенческих команд: трекинг задач, отчеты, созвоны. Делаем продуктовый интерфейс.",
    responsibilities: [
      "Верстать и собирать UI на React + TS",
      "Дорабатывать компоненты, формы и валидации",
      "Чинить баги и улучшать производительность",
    ],
    requirements: [
      "TypeScript на базовом/среднем уровне",
      "Понимание React (хуки, стейт, props)",
      "Внимание к UI-деталям (отступы, адаптив)",
    ],
    niceToHave: ["Опыт с Vite", "Тесты (Vitest/RTL)"],
    apply: {
      telegramUrl:
        "https://t.me/campusgrid_team?text=Здравствуйте!%20Откликаюсь%20на%20Frontend%20Intern%20(React)",
      email: "jobs@campusgrid.example",
    },
  },
  {
    id: "data-ml-onsite-spb",
    company: "SignalLab",
    roleTitle: "Data/ML Intern",
    salaryLabel: "от 75 000 ₽",
    salaryMin: 75000,
    paid: "Paid",
    format: "Onsite",
    city: "SPb",
    direction: "Data/ML",
    universities: ["ITMO", "SPbU", "HSE", "SPbPU"],
    programs: ["КТ", "ПМИ (ИТМО)", "ФКН"],
    stack: ["Python", "SQL", "Linux", "Docker"],
    courseMin: 3,
    courseMax: 4,
    season: "Лето 2026",
    duration: "3-4 месяца",
    locationLabel: "Санкт-Петербург",
    postedAtISO: "2026-01-29",
    shortPitch:
      "Модели для прогнозирования спроса. Много данных, много экспериментов, понятные метрики.",
    about:
      "SignalLab делает ML-решения для ретейла: прогнозирование, оптимизация, рекомендации. Ищем стажера в команду экспериментов.",
    responsibilities: [
      "Готовить датасеты и фичи",
      "Запускать эксперименты и сравнивать метрики",
      "Оформлять результаты в короткие отчеты",
    ],
    requirements: [
      "Python (pandas/numpy на базовом уровне)",
      "Понимание метрик и валидации",
      "Умение аккуратно оформлять выводы",
    ],
    niceToHave: ["PyTorch", "Опыт с MLflow", "Статистика"],
    apply: {
      telegramUrl: "https://t.me/signallab_hr?text=Привет!%20Откликаюсь%20на%20Data%2FML%20Intern",
      email: "ml-intern@signallab.example",
    },
  },
  {
    id: "devops-hybrid-moscow",
    company: "InfraForge",
    roleTitle: "DevOps Intern",
    salaryLabel: "от 70 000 ₽",
    salaryMin: 70000,
    paid: "Paid",
    format: "Hybrid",
    city: "Moscow",
    direction: "DevOps",
    universities: ["MIPT", "BMSTU", "MSU", "HSE", "MEPHI"],
    programs: ["ФИВТ", "ФПМИ", "ВМК", "ИВТ"],
    stack: ["Linux", "Docker", "Kubernetes", "Terraform"],
    courseMin: 3,
    courseMax: 4,
    minGpa: 7.0,
    season: "Весна 2026",
    duration: "3 месяца",
    locationLabel: "Москва",
    postedAtISO: "2026-02-05",
    asap: true,
    shortPitch:
      "Автоматизация пайплайнов и окружений. Много практики с контейнерами и k8s.",
    about:
      "InfraForge поддерживает CI/CD и платформенные сервисы для нескольких продуктовых команд. Ищем стажера, который любит автоматизацию.",
    responsibilities: [
      "Поддерживать CI/CD (пайплайны, артефакты)",
      "Собирать контейнеры и чарты (под присмотром)",
      "Разбирать инциденты и улучшать наблюдаемость",
    ],
    requirements: ["Linux базово", "Docker базово", "Git"],
    niceToHave: ["Kubernetes", "Helm", "Go или Bash"],
    apply: {
      telegramUrl: "https://t.me/infraforge_hr?text=Здравствуйте!%20Откликаюсь%20на%20DevOps%20Intern",
      email: "devops@infraforge.example",
    },
    hot: true,
  },
  {
    id: "mobile-android-remote",
    company: "PocketUni",
    roleTitle: "Android Intern (Kotlin)",
    salaryLabel: "неоплачиваемая",
    paid: "Unpaid",
    format: "Remote",
    city: "Any",
    direction: "Mobile",
    universities: ["HSE", "ITMO", "SPbU", "SPbPU", "INNO"],
    programs: ["ФКН", "КТ", "SE"],
    stack: ["Kotlin", "Linux"],
    courseMin: 1,
    courseMax: 2,
    season: "Весна 2026",
    duration: "6 недель",
    locationLabel: "Удаленно",
    postedAtISO: "2026-01-27",
    shortPitch: "Небольшой продукт. Хороший шанс собрать портфолио и поработать с релизом.",
    about:
      "PocketUni делает приложение-органайзер для пар и дедлайнов. Стажировка без оплаты, но с четкими задачами и ревью.",
    responsibilities: ["Делать экраны, навигацию, хранение настроек"],
    requirements: ["Базовый Kotlin или Java", "Желание доводить задачи до конца"],
    niceToHave: ["Опыт с Compose", "Публикация в Google Play (хоть раз)"],
    apply: {
      telegramUrl: "https://t.me/pocketuni_team?text=Привет!%20Откликаюсь%20на%20Android%20Intern%20(Kotlin)",
      email: "team@pocketuni.example",
    },
  },
  {
    id: "cpp-systems-onsite-moscow",
    company: "QuantNova",
    roleTitle: "C++ Intern (Systems)",
    salaryLabel: "от 100 000 ₽",
    salaryMin: 100000,
    paid: "Paid",
    format: "Onsite",
    city: "Moscow",
    direction: "Backend",
    universities: ["MSU", "MIPT", "BMSTU", "NSU"],
    programs: ["ВМК", "ФИВТ", "ФПМИ"],
    stack: ["C++", "Linux", "Docker"],
    courseMin: 3,
    courseMax: 4,
    season: "Лето 2026",
    duration: "3 месяца",
    locationLabel: "Москва",
    postedAtISO: "2026-02-02",
    asap: true,
    shortPitch:
      "Низкие задержки, профилирование, аккуратность. Не для всех, но очень “настоящая” инженерия.",
    about:
      "QuantNova делает высоконагруженные системы обработки данных. Ищем стажера в платформенную команду.",
    responsibilities: [
      "Писать и оптимизировать C++ код",
      "Профилировать и убирать узкие места",
      "Делать небольшие утилиты и инструменты",
    ],
    requirements: ["C++ (STL)", "Linux базово", "Алгоритмы и структуры данных"],
    niceToHave: ["Опыт с perf", "Сетевые основы"],
    apply: {
      telegramUrl:
        "https://t.me/quantnova_hr?text=Здравствуйте!%20Откликаюсь%20на%20C%2B%2B%20Intern%20(Systems)",
      email: "cpp@quantnova.example",
    },
  },
  {
    id: "ai-ml-remote",
    company: "VectorAI",
    roleTitle: "AI Intern (LLM / NLP)",
    salaryLabel: "от 90 000 ₽",
    salaryMin: 90000,
    paid: "Paid",
    format: "Remote",
    city: "Any",
    direction: "AI",
    universities: ["HSE", "MIPT", "ITMO", "MSU", "NSU", "INNO"],
    programs: ["ФКН", "ФИВТ", "КТ", "ПМИ"],
    stack: ["Python", "Linux", "Docker"],
    courseMin: 2,
    courseMax: 4,
    minGpa: 7.0,
    season: "Лето 2026",
    duration: "2-3 месяца",
    locationLabel: "Удаленно",
    postedAtISO: "2026-02-06",
    asap: true,
    shortPitch:
      "RAG, эмбеддинги, оценка качества. Нужны аккуратные эксперименты и нормальные заметки.",
    about:
      "VectorAI делает LLM-помощника для корпоративных баз знаний. Ищем стажера, который любит экспериментировать и фиксировать результаты.",
    responsibilities: [
      "Собирать пайплайн RAG (ингест, индексация, retrieval)",
      "Делать эксперименты и оценку качества ответов",
      "Оформлять выводы и улучшать промпты/шаблоны",
    ],
    requirements: ["Python", "Базовое понимание ML/NLP", "Внимательность к данным и метрикам"],
    niceToHave: ["Опыт с vector DB", "PyTorch", "LLM eval"],
    apply: {
      telegramUrl:
        "https://t.me/vectorai_hr?text=Здравствуйте!%20Откликаюсь%20на%20AI%20Intern%20(LLM%2FNLP)",
      email: "ai@vectorai.example",
    },
    hot: true,
  },
  {
    id: "sber-front-hybrid-moscow",
    company: "SberTech",
    roleTitle: "Frontend Intern (React)",
    salaryLabel: "от 75 000 ₽",
    salaryMin: 75000,
    paid: "Paid",
    format: "Hybrid",
    city: "Moscow",
    direction: "Frontend",
    universities: ["HSE", "MSU", "MIPT", "BMSTU", "MISIS", "MIREA"],
    programs: ["ИВТ", "ПИ", "ФКН"],
    stack: ["Git", "HTML", "CSS", "TypeScript", "React", "REST"],
    courseMin: 2,
    courseMax: 4,
    minGpa: 6.8,
    season: "Весна 2026",
    duration: "2-3 месяца",
    locationLabel: "Москва",
    postedAtISO: "2026-02-04",
    asap: true,
    shortPitch: "Делаем интерфейсы для внутренней платформы. Много практики и ревью.",
    about:
      "Команда делает продуктовый UI для внутренних сервисов. Нужен стажер, который аккуратно верстает и любит понятные состояния.",
    responsibilities: [
      "Собирать UI на React + TypeScript",
      "Дорабатывать формы и валидации",
      "Фиксить баги и улучшать UX",
    ],
    requirements: ["Базовый TypeScript", "React (хуки)", "HTML/CSS"],
    niceToHave: ["Опыт с Vite", "Figma/дизайн-системы"],
    apply: {
      telegramUrl: "https://t.me/sbertech_hr?text=Здравствуйте!%20Откликаюсь%20на%20Frontend%20Intern%20(React)",
      email: "frontend@sbertech.example",
    },
  },
  {
    id: "yandex-backend-remote-go",
    company: "Yandex",
    roleTitle: "Backend Intern (Go)",
    salaryLabel: "от 90 000 ₽",
    salaryMin: 90000,
    paid: "Paid",
    format: "Remote",
    city: "Any",
    direction: "Backend",
    universities: ["HSE", "MSU", "MIPT", "ITMO", "NSU", "SPbU"],
    programs: ["ФКН", "ПМИ", "ИВТ"],
    stack: ["Go", "Git", "REST", "SQL", "Docker", "Linux"],
    courseMin: 2,
    courseMax: 4,
    minGpa: 7.2,
    season: "Лето 2026",
    duration: "3 месяца",
    locationLabel: "Удаленно",
    postedAtISO: "2026-02-05",
    asap: true,
    shortPitch: "Сервисы и API, логирование и метрики. Нормальный прод-опыт на Go.",
    about:
      "Команда делает backend-сервисы. Дадим наставника и задачи, которые реально доходят до релиза.",
    responsibilities: ["Писать Go-сервисы", "Работать с SQL", "Добавлять метрики/логи"],
    requirements: ["Основы программирования", "Git", "Понимание HTTP"],
    niceToHave: ["Docker", "Linux", "Опыт с Go"],
    apply: {
      telegramUrl: "https://t.me/yandex_hr?text=Здравствуйте!%20Откликаюсь%20на%20Backend%20Intern%20(Go)",
      email: "backend@yandex.example",
    },
  },
  {
    id: "tbank-ml-hybrid-spb",
    company: "T-Bank",
    roleTitle: "Data/ML Intern",
    salaryLabel: "от 85 000 ₽",
    salaryMin: 85000,
    paid: "Paid",
    format: "Hybrid",
    city: "SPb",
    direction: "Data/ML",
    universities: ["ITMO", "SPbU", "SPbPU", "HSE", "MIPT"],
    programs: ["ПМИ", "КТ", "ФИВТ"],
    stack: ["Python", "SQL", "Git", "Linux"],
    courseMin: 3,
    courseMax: 4,
    season: "Лето 2026",
    duration: "3-4 месяца",
    locationLabel: "Санкт-Петербург",
    postedAtISO: "2026-02-01",
    shortPitch: "Эксперименты, метрики, датасеты. Без воды, с понятными задачами.",
    about:
      "Ищем стажера в команду экспериментов: подготовка данных, запуск сравнений, оформление выводов.",
    responsibilities: ["Готовить данные", "Запускать эксперименты", "Оформлять результаты"],
    requirements: ["Python", "Базовый SQL", "Аккуратность"],
    niceToHave: ["pandas", "Jupyter", "Базовая статистика"],
    apply: {
      telegramUrl: "https://t.me/tbank_hr?text=Здравствуйте!%20Откликаюсь%20на%20Data%2FML%20Intern",
      email: "ml@tbank.example",
    },
  },
  {
    id: "itmo-mobile-onsite-spb",
    company: "StudentLab",
    roleTitle: "Mobile Intern (Android)",
    salaryLabel: "неоплачиваемая",
    paid: "Unpaid",
    format: "Onsite",
    city: "SPb",
    direction: "Mobile",
    universities: ["ITMO", "SPbU", "SPbPU", "LETI"],
    programs: ["КТ", "ИВТ", "SE"],
    stack: ["Kotlin", "Git", "REST"],
    courseMin: 1,
    courseMax: 3,
    season: "Весна 2026",
    duration: "6 недель",
    locationLabel: "Санкт-Петербург",
    postedAtISO: "2026-01-30",
    shortPitch: "Небольшое приложение, много практики. Хорошо для портфолио.",
    about:
      "Команда собирает студенческий продукт. Стажировка без оплаты, но с понятными задачами и ревью.",
    responsibilities: ["Собирать экраны", "Навигация", "Интеграция с API"],
    requirements: ["Kotlin базово", "Желание учиться", "Git"],
    niceToHave: ["Compose", "Опыт публикации"],
    apply: {
      telegramUrl: "https://t.me/studentlab_team?text=Привет!%20Откликаюсь%20на%20Mobile%20Intern%20(Android)",
      email: "mobile@studentlab.example",
    },
  },
  {
    id: "inno-devops-remote",
    company: "InnoCloud",
    roleTitle: "DevOps Intern",
    salaryLabel: "от 65 000 ₽",
    salaryMin: 65000,
    paid: "Paid",
    format: "Remote",
    city: "Any",
    direction: "DevOps",
    universities: ["INNO", "KFU", "HSE", "ITMO", "MIPT"],
    programs: ["ИВТ", "ПИ"],
    stack: ["Linux", "Docker", "Git", "Terraform"],
    courseMin: 2,
    courseMax: 4,
    season: "Весна 2026",
    duration: "2 месяца",
    locationLabel: "Удаленно",
    postedAtISO: "2026-02-02",
    asap: true,
    shortPitch: "CI/CD, инфраструктура и окружения. Больше практики, меньше теории.",
    about:
      "Команда поддерживает окружения и пайплайны. Ищем стажера, которому нравится автоматизация.",
    responsibilities: ["Поддержка CI/CD", "Docker", "Автоматизация скриптами"],
    requirements: ["Linux базово", "Git", "Понимание сетей на базовом уровне"],
    niceToHave: ["Terraform", "Kubernetes"],
    apply: {
      telegramUrl: "https://t.me/innocloud_hr?text=Здравствуйте!%20Откликаюсь%20на%20DevOps%20Intern",
      email: "devops@innocloud.example",
    },
  },
  {
    id: "security-intern-moscow",
    company: "SafeGate",
    roleTitle: "Security Intern",
    salaryLabel: "от 90 000 ₽",
    salaryMin: 90000,
    paid: "Paid",
    format: "Hybrid",
    city: "Moscow",
    direction: "Security",
    universities: ["MEPHI", "HSE", "MSU", "MIREA", "MTUCI"],
    programs: ["ИБ", "ИВТ"],
    stack: ["Linux", "Git", "REST"],
    courseMin: 3,
    courseMax: 4,
    season: "Осень 2026",
    duration: "2 месяца",
    locationLabel: "Москва",
    postedAtISO: "2026-02-06",
    shortPitch: "Пентест-заметки, базовые проверки, автоматизация отчетов. Без героизма.",
    about:
      "Ищем стажера в security: базовые проверки, оформление находок, помощь в автоматизации.",
    responsibilities: ["Проверки по чек-листу", "Оформление отчетов", "Автоматизация мелочей"],
    requirements: ["Linux базово", "Внимательность", "Коммуникация"],
    niceToHave: ["OWASP Top 10 (понимание)", "CTF-опыт"],
    apply: {
      telegramUrl: "https://t.me/safegate_hr?text=Здравствуйте!%20Откликаюсь%20на%20Security%20Intern",
      email: "security@safegate.example",
    },
  },
  {
    id: "backend-csharp-kazan",
    company: "VolgaSoft",
    roleTitle: "Backend Intern (C#/.NET)",
    salaryLabel: "от 60 000 ₽",
    salaryMin: 60000,
    paid: "Paid",
    format: "Onsite",
    city: "Kazan",
    direction: "Backend",
    universities: ["KFU", "INNO"],
    programs: ["ПИ", "ИВТ"],
    stack: ["C#", ".NET", "SQL", "Git"],
    courseMin: 2,
    courseMax: 4,
    season: "Осень 2026",
    duration: "2-3 месяца",
    locationLabel: "Казань",
    postedAtISO: "2026-02-03",
    shortPitch: "API на .NET, работа с базой, ревью. Хороший “вход” в backend.",
    about:
      "Команда делает сервисы для внутренней платформы. На стажировке будет наставник и понятные задачи.",
    responsibilities: ["Писать API", "SQL-запросы", "Фикс багов"],
    requirements: ["C# базово", "SQL базово", "Git"],
    niceToHave: ["Docker", "REST"],
    apply: {
      telegramUrl: "https://t.me/volgasoft_hr?text=Здравствуйте!%20Откликаюсь%20на%20Backend%20Intern%20(C%23%2F.NET)",
      email: "backend@volgasoft.example",
    },
  },
  {
    id: "react-remote-student",
    company: "OpenCampus",
    roleTitle: "Frontend Intern (React/TS)",
    salaryLabel: "от 60 000 ₽",
    salaryMin: 60000,
    paid: "Paid",
    format: "Remote",
    city: "Any",
    direction: "Frontend",
    universities: ["HSE", "ITMO", "SPbU", "NSU", "URFU", "KFU"],
    programs: ["ИВТ", "ПИ", "SE"],
    stack: ["TypeScript", "React", "Git", "REST"],
    courseMin: 1,
    courseMax: 4,
    season: "Осень 2026",
    duration: "8 недель",
    locationLabel: "Удаленно",
    postedAtISO: "2026-02-02",
    shortPitch: "Компоненты, формы, состояние. Делаем аккуратный UI для студентов.",
    about:
      "OpenCampus делает сервис для учебных команд. Нужен стажер на фронт: компоненты, формы, багфиксы.",
    responsibilities: ["UI на React", "Формы/валидации", "Багфиксы"],
    requirements: ["TypeScript базово", "React", "Git"],
    niceToHave: ["Next.js", "CSS аккуратно"],
    apply: {
      telegramUrl: "https://t.me/opencampus_hr?text=Здравствуйте!%20Откликаюсь%20на%20Frontend%20Intern%20(React%2FTS)",
      email: "frontend@opencampus.example",
    },
  },
  {
    id: "novosibirsk-python-data",
    company: "SiberData",
    roleTitle: "Data Intern (Python)",
    salaryLabel: "от 55 000 ₽",
    salaryMin: 55000,
    paid: "Paid",
    format: "Onsite",
    city: "Novosibirsk",
    direction: "Data/ML",
    universities: ["NSU", "TSU", "TPU"],
    programs: ["ПМИ", "ИВТ"],
    stack: ["Python", "SQL", "Git"],
    courseMin: 2,
    courseMax: 4,
    season: "Весна 2026",
    duration: "2 месяца",
    locationLabel: "Новосибирск",
    postedAtISO: "2026-02-01",
    shortPitch: "Данные, SQL и простые метрики. Отлично для первого опыта в data.",
    about:
      "Команда делает аналитику для внутреннего продукта. На стажировке будешь работать с данными и простыми отчетами.",
    responsibilities: ["SQL", "Подготовка датасетов", "Простые отчеты"],
    requirements: ["Python", "SQL базово", "Аккуратность"],
    niceToHave: ["pandas", "Jupyter"],
    apply: {
      telegramUrl: "https://t.me/siberdata_hr?text=Здравствуйте!%20Откликаюсь%20на%20Data%20Intern%20(Python)",
      email: "data@siberdata.example",
    },
  },
  {
    id: "ekb-go-backend",
    company: "UralStack",
    roleTitle: "Backend Intern (Go)",
    salaryLabel: "от 70 000 ₽",
    salaryMin: 70000,
    paid: "Paid",
    format: "Hybrid",
    city: "Yekaterinburg",
    direction: "Backend",
    universities: ["URFU"],
    programs: ["ИВТ", "ПИ"],
    stack: ["Go", "Git", "REST", "SQL"],
    courseMin: 2,
    courseMax: 4,
    season: "Лето 2026",
    duration: "3 месяца",
    locationLabel: "Екатеринбург",
    postedAtISO: "2026-02-03",
    asap: true,
    shortPitch: "Go + API + база. Нормальные задачи и ревью без стресса.",
    about:
      "UralStack делает backend для внутреннего продукта. Стажер будет писать API и помогать с интеграциями.",
    responsibilities: ["Go сервисы", "REST API", "SQL"],
    requirements: ["Git", "HTTP/REST", "Желание учиться"],
    niceToHave: ["Docker", "Linux"],
    apply: {
      telegramUrl: "https://t.me/uralstack_hr?text=Здравствуйте!%20Откликаюсь%20на%20Backend%20Intern%20(Go)",
      email: "backend@uralstack.example",
    },
  },
  {
    id: "qa-automation-moscow",
    company: "TestCraft",
    roleTitle: "QA Intern (Automation)",
    salaryLabel: "от 50 000 ₽",
    salaryMin: 50000,
    paid: "Paid",
    format: "Hybrid",
    city: "Moscow",
    direction: "Backend",
    universities: ["HSE", "MIREA", "MTUCI", "MISIS"],
    programs: ["ИВТ"],
    stack: ["Git", "REST", "JSON"],
    courseMin: 1,
    courseMax: 4,
    season: "Весна 2026",
    duration: "2 месяца",
    locationLabel: "Москва",
    postedAtISO: "2026-02-02",
    shortPitch: "Автотесты API и простые проверки. Хорошо для первого опыта в QA.",
    about:
      "Команда занимается качеством API. На стажировке будешь писать простые автотесты и помогать с регрессией.",
    responsibilities: ["Проверки API", "Автотесты", "Багрепорты"],
    requirements: ["Аккуратность", "Понимание HTTP", "Git базово"],
    niceToHave: ["Python или JS"],
    apply: {
      telegramUrl: "https://t.me/testcraft_hr?text=Здравствуйте!%20Откликаюсь%20на%20QA%20Intern",
      email: "qa@testcraft.example",
    },
  },
  {
    id: "android-kazan-kotlin",
    company: "KazanApps",
    roleTitle: "Android Intern (Kotlin)",
    salaryLabel: "от 45 000 ₽",
    salaryMin: 45000,
    paid: "Paid",
    format: "Onsite",
    city: "Kazan",
    direction: "Mobile",
    universities: ["KFU", "INNO"],
    programs: ["ИВТ", "SE"],
    stack: ["Kotlin", "Git", "REST"],
    courseMin: 1,
    courseMax: 4,
    season: "Лето 2026",
    duration: "2 месяца",
    locationLabel: "Казань",
    postedAtISO: "2026-02-01",
    shortPitch: "Экраны, навигация, API. Хороший старт в mobile-разработке.",
    about:
      "Команда делает приложение для локального сервиса. На стажировке будет наставник и регулярные ревью.",
    responsibilities: ["Экраны", "Навигация", "Интеграция с API"],
    requirements: ["Kotlin базово", "Git", "Желание учиться"],
    niceToHave: ["Compose", "Опыт с Android Studio"],
    apply: {
      telegramUrl: "https://t.me/kazanapps_hr?text=Здравствуйте!%20Откликаюсь%20на%20Android%20Intern%20(Kotlin)",
      email: "android@kazanapps.example",
    },
  },
  {
    id: "ai-remote-prompt",
    company: "PromptWorks",
    roleTitle: "AI Intern (RAG)",
    salaryLabel: "от 85 000 ₽",
    salaryMin: 85000,
    paid: "Paid",
    format: "Remote",
    city: "Any",
    direction: "AI",
    universities: ["HSE", "MIPT", "ITMO", "MSU", "SKOLTECH"],
    programs: ["ПМИ", "ФКН"],
    stack: ["Python", "Git", "JSON", "REST"],
    courseMin: 2,
    courseMax: 4,
    season: "Осень 2026",
    duration: "2 месяца",
    locationLabel: "Удаленно",
    postedAtISO: "2026-02-05",
    asap: true,
    shortPitch: "RAG-пайплайн, оценка качества, аккуратные эксперименты и заметки.",
    about:
      "Команда делает LLM-помощника для базы знаний. Стажер будет помогать с пайплайном retrieval и оценкой качества.",
    responsibilities: ["Эксперименты", "Оценка качества", "Интеграции"],
    requirements: ["Python", "Аккуратность", "Git"],
    niceToHave: ["pandas", "Опыт с LLM"],
    apply: {
      telegramUrl: "https://t.me/promptworks_hr?text=Здравствуйте!%20Откликаюсь%20на%20AI%20Intern%20(RAG)",
      email: "ai@promptworks.example",
    },
  },
  {
    id: "devops-spb-junior",
    company: "DeployNow",
    roleTitle: "DevOps Intern",
    salaryLabel: "от 60 000 ₽",
    salaryMin: 60000,
    paid: "Paid",
    format: "Onsite",
    city: "SPb",
    direction: "DevOps",
    universities: ["ITMO", "SPbU", "SPbPU", "LETI"],
    programs: ["ИВТ"],
    stack: ["Linux", "Docker", "Git", "Terraform"],
    courseMin: 2,
    courseMax: 4,
    season: "Лето 2026",
    duration: "3 месяца",
    locationLabel: "Санкт-Петербург",
    postedAtISO: "2026-02-03",
    shortPitch: "CI/CD и окружения. Много практики, минимум бюрократии.",
    about:
      "Команда помогает продуктовым разработчикам с деплоем и инфраструктурой. Стажер будет работать с контейнерами и пайплайнами.",
    responsibilities: ["CI/CD", "Docker", "Скрипты"],
    requirements: ["Linux базово", "Git"],
    niceToHave: ["Kubernetes"],
    apply: {
      telegramUrl: "https://t.me/deploynow_hr?text=Здравствуйте!%20Откликаюсь%20на%20DevOps%20Intern",
      email: "devops@deploynow.example",
    },
  },
  {
    id: "fullstack-remote-node",
    company: "MiniSaaS",
    roleTitle: "Fullstack Intern (Node/React)",
    salaryLabel: "от 65 000 ₽",
    salaryMin: 65000,
    paid: "Paid",
    format: "Remote",
    city: "Any",
    direction: "Frontend",
    universities: ["HSE", "ITMO", "SPbU", "URFU", "KFU"],
    programs: ["ИВТ", "ПИ"],
    stack: ["Node.js", "React", "TypeScript", "REST", "Git"],
    courseMin: 2,
    courseMax: 4,
    season: "Весна 2026",
    duration: "2 месяца",
    locationLabel: "Удаленно",
    postedAtISO: "2026-02-02",
    shortPitch: "Небольшой SaaS: формы, API, база. Отлично для первого fullstack опыта.",
    about:
      "MiniSaaS делает небольшой продукт. Стажер будет помогать с UI и API, фиксить баги и допиливать фичи.",
    responsibilities: ["React UI", "Node API", "Интеграции"],
    requirements: ["TypeScript базово", "Git", "Понимание HTTP"],
    niceToHave: ["SQL", "Docker"],
    apply: {
      telegramUrl: "https://t.me/minisaas_hr?text=Здравствуйте!%20Откликаюсь%20на%20Fullstack%20Intern",
      email: "jobs@minisaas.example",
    },
  },
  {
    id: "cplus-plus-onsite-moscow",
    company: "CoreSystems",
    roleTitle: "C++ Intern",
    salaryLabel: "от 95 000 ₽",
    salaryMin: 95000,
    paid: "Paid",
    format: "Onsite",
    city: "Moscow",
    direction: "Backend",
    universities: ["MSU", "MIPT", "BMSTU", "NSU"],
    programs: ["ПМИ", "ВМК"],
    stack: ["C++", "Linux", "Git"],
    courseMin: 3,
    courseMax: 4,
    season: "Осень 2026",
    duration: "3 месяца",
    locationLabel: "Москва",
    postedAtISO: "2026-02-04",
    shortPitch: "Платформенный C++: профилирование и оптимизация. Реальная инженерия.",
    about:
      "Команда делает платформенные компоненты. На стажировке будет наставник и задачи по оптимизации.",
    responsibilities: ["C++ код", "Профилирование", "Багфиксы"],
    requirements: ["C++ (STL)", "Алгоритмы базово", "Linux базово"],
    niceToHave: ["Опыт с perf"],
    apply: {
      telegramUrl: "https://t.me/coresystems_hr?text=Здравствуйте!%20Откликаюсь%20на%20C%2B%2B%20Intern",
      email: "cpp@coresystems.example",
    },
  },
  {
    id: "junior-java-onsite-moscow",
    company: "FinStack",
    roleTitle: "Backend Intern (Java)",
    salaryLabel: "от 80 000 ₽",
    salaryMin: 80000,
    paid: "Paid",
    format: "Hybrid",
    city: "Moscow",
    direction: "Backend",
    universities: ["HSE", "MSU", "MISIS", "MIREA", "MAI", "MEI"],
    programs: ["ИВТ", "ПИ"],
    stack: ["Java", "Git", "REST", "SQL"],
    courseMin: 2,
    courseMax: 4,
    season: "Лето 2026",
    duration: "3 месяца",
    locationLabel: "Москва",
    postedAtISO: "2026-02-02",
    asap: true,
    shortPitch: "Java + API + база. Хороший первый опыт в финтехе.",
    about:
      "Команда делает backend-сервисы для платежей. На стажировке будут ревью и понятные задачи.",
    responsibilities: ["API на Java", "SQL", "Интеграции"],
    requirements: ["Java базово", "Git", "HTTP"],
    niceToHave: ["Docker"],
    apply: {
      telegramUrl: "https://t.me/finstack_hr?text=Здравствуйте!%20Откликаюсь%20на%20Backend%20Intern%20(Java)",
      email: "java@finstack.example",
    },
  },
  {
    id: "design-frontend-spb",
    company: "UIForge",
    roleTitle: "Frontend Intern (UI)",
    salaryLabel: "от 55 000 ₽",
    salaryMin: 55000,
    paid: "Paid",
    format: "Hybrid",
    city: "SPb",
    direction: "Frontend",
    universities: ["SPbU", "ITMO", "SPbPU", "LETI", "SUAI"],
    programs: ["ИВТ", "SE"],
    stack: ["HTML", "CSS", "JavaScript", "Git"],
    courseMin: 1,
    courseMax: 4,
    season: "Весна 2026",
    duration: "2 месяца",
    locationLabel: "Санкт-Петербург",
    postedAtISO: "2026-02-01",
    shortPitch: "Верстка и компоненты. Для тех, кто любит пиксели и аккуратность.",
    about:
      "Команда делает UI-компоненты и страницы. Стажер будет верстать и доводить до хорошего качества.",
    responsibilities: ["Верстка", "Компоненты", "Багфиксы"],
    requirements: ["HTML/CSS", "JavaScript базово", "Аккуратность"],
    niceToHave: ["TypeScript", "Figma"],
    apply: {
      telegramUrl: "https://t.me/uiforge_hr?text=Здравствуйте!%20Откликаюсь%20на%20Frontend%20Intern%20(UI)",
      email: "ui@uiforge.example",
    },
  },
  {
    id: "data-remote-analytics",
    company: "MetricHub",
    roleTitle: "Analytics Intern",
    salaryLabel: "от 50 000 ₽",
    salaryMin: 50000,
    paid: "Paid",
    format: "Remote",
    city: "Any",
    direction: "Data/ML",
    universities: ["HSE", "MSU", "ITMO", "SPbU", "NNSU", "URFU"],
    programs: ["ПМИ", "ИВТ"],
    stack: ["SQL", "Git", "JSON"],
    courseMin: 2,
    courseMax: 4,
    season: "Осень 2026",
    duration: "2 месяца",
    locationLabel: "Удаленно",
    postedAtISO: "2026-02-03",
    shortPitch: "SQL и метрики продукта. Отличный старт в аналитике.",
    about:
      "Команда делает продуктовую аналитику. Стажер будет помогать с запросами и отчетами.",
    responsibilities: ["SQL запросы", "Метрики", "Отчеты"],
    requirements: ["SQL базово", "Аккуратность"],
    niceToHave: ["Python"],
    apply: {
      telegramUrl: "https://t.me/metrichub_hr?text=Здравствуйте!%20Откликаюсь%20на%20Analytics%20Intern",
      email: "analytics@metrichub.example",
    },
  },
  {
    id: "rust-remote-systems",
    company: "ByteKernel",
    roleTitle: "Systems Intern",
    salaryLabel: "от 95 000 ₽",
    salaryMin: 95000,
    paid: "Paid",
    format: "Remote",
    city: "Any",
    direction: "Backend",
    universities: ["MIPT", "MSU", "HSE", "NSU"],
    programs: ["ПМИ"],
    stack: ["Git", "Linux", "REST"],
    courseMin: 3,
    courseMax: 4,
    season: "Лето 2026",
    duration: "3 месяца",
    locationLabel: "Удаленно",
    postedAtISO: "2026-02-06",
    shortPitch: "Системная разработка и инструменты. Подойдет любителям низкого уровня.",
    about:
      "Команда делает внутренние инструменты. Стажер будет писать утилиты и помогать с инфраструктурой разработки.",
    responsibilities: ["Инструменты", "Скрипты", "Багфиксы"],
    requirements: ["Linux базово", "Git", "Аккуратность"],
    niceToHave: ["Любой опыт системного программирования"],
    apply: {
      telegramUrl: "https://t.me/bytekernel_hr?text=Здравствуйте!%20Откликаюсь%20на%20Systems%20Intern",
      email: "systems@bytekernel.example",
    },
  },
  {
    id: "intern-ops-moscow",
    company: "CloudDesk",
    roleTitle: "Platform Intern",
    salaryLabel: "от 70 000 ₽",
    salaryMin: 70000,
    paid: "Paid",
    format: "Hybrid",
    city: "Moscow",
    direction: "DevOps",
    universities: ["HSE", "MIPT", "MEPHI", "BMSTU", "MISIS"],
    programs: ["ИВТ"],
    stack: ["Docker", "Linux", "Git"],
    courseMin: 2,
    courseMax: 4,
    season: "Весна 2026",
    duration: "2 месяца",
    locationLabel: "Москва",
    postedAtISO: "2026-02-05",
    asap: true,
    shortPitch: "Платформа, окружения и контейнеры. Реальная практика.",
    about:
      "Команда поддерживает платформу для разработчиков. Стажер будет помогать с окружениями и контейнерами.",
    responsibilities: ["Docker", "Linux", "Автоматизация"],
    requirements: ["Linux базово", "Git"],
    niceToHave: ["Terraform"],
    apply: {
      telegramUrl: "https://t.me/clouddesk_hr?text=Здравствуйте!%20Откликаюсь%20на%20Platform%20Intern",
      email: "platform@clouddesk.example",
    },
  },
  {
    id: "kotlin-backend-remote",
    company: "ServicePocket",
    roleTitle: "Backend Intern (Kotlin)",
    salaryLabel: "от 80 000 ₽",
    salaryMin: 80000,
    paid: "Paid",
    format: "Remote",
    city: "Any",
    direction: "Backend",
    universities: ["HSE", "ITMO", "SPbU", "MIPT", "NSU"],
    programs: ["ПИ", "ИВТ"],
    stack: ["Kotlin", "Git", "REST", "SQL"],
    courseMin: 2,
    courseMax: 4,
    season: "Лето 2026",
    duration: "3 месяца",
    locationLabel: "Удаленно",
    postedAtISO: "2026-02-02",
    shortPitch: "Сервисы на Kotlin, база и API. Отличный старт в backend.",
    about:
      "Команда делает сервисы для небольшого продукта. На стажировке будут ревью и понятные задачи.",
    responsibilities: ["API", "SQL", "Интеграции"],
    requirements: ["Kotlin или Java базово", "Git", "HTTP"],
    niceToHave: ["Docker"],
    apply: {
      telegramUrl: "https://t.me/servicepocket_hr?text=Здравствуйте!%20Откликаюсь%20на%20Backend%20Intern%20(Kotlin)",
      email: "backend@servicepocket.example",
    },
  },
  {
    id: "spbu-security-spb",
    company: "RedTeamLab",
    roleTitle: "Security Intern (Blue Team)",
    salaryLabel: "от 55 000 ₽",
    salaryMin: 55000,
    paid: "Paid",
    format: "Onsite",
    city: "SPb",
    direction: "Security",
    universities: ["SPbU", "ITMO", "LETI", "SUAI", "SPbPU"],
    programs: ["ИБ"],
    stack: ["Linux", "Git"],
    courseMin: 2,
    courseMax: 4,
    season: "Лето 2026",
    duration: "2 месяца",
    locationLabel: "Санкт-Петербург",
    postedAtISO: "2026-02-03",
    shortPitch: "Логи, простые правила, оформление инцидентов. Хороший старт в security.",
    about:
      "Команда занимается мониторингом и реагированием. Стажер будет помогать с разбором логов и оформлением кейсов.",
    responsibilities: ["Разбор логов", "Чек-листы", "Отчеты"],
    requirements: ["Linux базово", "Внимательность"],
    niceToHave: ["Сетевые основы"],
    apply: {
      telegramUrl: "https://t.me/redteamlab_hr?text=Здравствуйте!%20Откликаюсь%20на%20Security%20Intern%20(Blue%20Team)",
      email: "blue@redteamlab.example",
    },
  },
];
